### ISSUE TITLE
設定「plugin»linebreak2»linebreak」が認識されない（The setting plugin»linebreak2»linebreak doesn't work well）

### ISSUE THREAD

**Issue by hokkaidoperson** [ssahara/dw-plugin-linebreak2#2]
linebreak2プラグインをインストールし、設定を施したのですが、「改行文字の取り扱い方」を「brタグに置換」に設定しても置換されていないようです（ソースコードによると、改行文字 ¥n が消える〔「取り除く」に設定した時と同じ動作になる〕模様。~~[状況](https://jdwiki.hkdyukkuri.space/s/sm31854709)~~）。
LINEBREAKマクロを指定した場合は正常に置き換えられます（~~[マクロ指定時の状況](https://jdwiki.hkdyukkuri.space/wiki/syntax)~~）。

renderer_xhtmlはちゃんとlinebreak2に設定しています。
テンプレートはbootstrap3を使用しています。
調査・対応をお願い出来ますでしょうか。

※一時的に、linebreak2プラグインの利用をとりやめxbrプラグインに戻しています。

**Comment by ssahara** [comment]
@hokkaidoperson 
レポジトリを最新化していなかったようでした…（本日更新しました）。
「改行文字の取り扱い方」を「brタグに置換」に設定した場合、意味がある出力がなされる場合のみ`<br>`タグを出力するようにしています。この点がxbrプラグインとは異なります。

**Comment by hokkaidoperson** [comment]
確認・対応ありがとうございます。

プラグインの動作が正常になっている事を確認しました。
「意味がある出力がなされる場合」というのは、例えば「行末が「/」等の記号の場合には自動改行をしない」という解釈で合っていますでしょうか？

**Comment by ssahara** [comment]
返信ありがとうございます。
「意味がある出力がなされる場合」は、半角スペースやタブ、改行などの連続のことで、HTMLの表示時に半角スペース1文字として扱われるようなケースです。

**Comment by hokkaidoperson** [comment]
分かりました。対応ありがとうございます。
